apiVersion: v1
kind: Namespace
metadata:
  name: harshitha-namespace #-> Give your own namespace with your name Ex: ram-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harshitha-flask-app #-> Give your deployment name Ex: <your-name-app-name>
  namespace: harshitha-namespace #-> Give your own namespace with your name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app #-> Give your app name app: java-1
  template:
    metadata:
      labels:
        app: flask-app #-> Give your app name app: java-1
    spec:
      containers:
      - name: harshitha-container #-> Give your container name Ex: java-1
        image: harshitha/simple-flask-api #-> Give your dockerhub image name basically with your username/app:1.0
        ports:
        - containerPort: 80 #-> make suer your container port properly ex: 8000 or 3000 depends on the container running.
        
--- 
apiVersion: v1
kind: Service
metadata:
  name: harshitha-flask-app-svc #-> Give your service name Ex: <your-name+app-name-svc
  namespace: harshitha-namespace #-> Give your own namespace with your name
spec:
  selector:
    app: flask-app #-> Give your app name app: java-1
  ports:
    - protocol: TCP
      port: 80 #-> keep the same port for service from pod port as well for best practice.
      targetPort: 80  #-> make suer your container port properly ex: 8000 or 3000 depends on the container running.
  type: LoadBalancer # -> For cloud
